name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with JUCE.
  - type: textarea
    id: repro
    attributes:
      label: Detailed steps on how to reproduce the bug
      description: If possible please use already existing JUCE code such as the examples or the demo plug-in
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is the expected behaviour?
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: Operating system
      description: What operating systems do you see the bug on?
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: iOS
        - label: Android
        - label: Other
    validations:
      required: true
  - type: textarea
    id: osversion
    attributes:
      label: What version of the operating system?
    validations:
      required: true
  - type: checkboxes
    id: architecture
    attributes:
      label: Architecture
      description: What type of machines do you see the bug on?
      options:
        - label: x86_64
        - label: ARM
        - label: Other
        - label: 64-bit
        - label: 32-bit
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Stacktrace
      description: Please copy and paste any relevant stack trace. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: pluginformat
    attributes:
      label: Plug-in format (if applicable)
      options:
        - label: VST2
        - label: VST3
        - label: AU
        - label: AUv3
        - label: AAX
        - label: LV2
        - label: Standalone
  - type: textarea
    id: pluginhosts
    attributes:
      label: Plug-in host applications (DAW) (if applicable)
  - type: checkboxes
    id: developbranch
    attributes:
      label: Tested against the `develop` branch
      description: We have often already fixed bugs on our `develop` branch. Please confirm if you have tested with the latest commit.
      options:
        - label: I can reproduce the bug on the `develop` branch
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://berlincodeofconduct.org/)
      options:
        - label: I agree to follow the Code of Conduct
          required: true

